version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: slotspot_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=_password
      - POSTGRES_DB=slotspot
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - slotspot-network

volumes:
  postgres-data:

networks:
  slotspot-network:
    driver: bridge